version: "3.9"

services:
  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  api:
    image: ghcr.io/oj-washingtone/savannah-store/api-service:latest
    container_name: savannah_store_api
    depends_on:
      - db
    env_file:
      - .env
    # environment:
    #   DB_HOST: db
    #   DB_PORT: 5432
    #   DB_USER: ${DB_USER}
    #   DB_PASSWORD: ${DB_PASSWORD}
    #   DB_NAME: ${DB_NAME}
    #   AUTH0_DOMAIN: ${AUTH0_DOMAIN}
    #   AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
    #   AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
    #   AUTH0_CALLBACK_URL: ${AUTH0_CALLBACK_URL}
    #   RESEND_KEY: ${RESEND_KEY}
    #   ADMIN_EMAIL: ${ADMIN_EMAIL}
    #   AFRICASTALKING_API_KEY: ${AFRICASTALKING_API_KEY}
    #   AFRICASTALKING_URL: ${AFRICASTALKING_URL}
    #   AFRICASTALKING_USERNAME: ${AFRICASTALKING_USERNAME}
    ports:
      - "8080:8080"
    restart: always

  migrate:
    image: migrate/migrate
    depends_on:
      - db
    volumes:
      - ./migrations:/migrations
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    entrypoint: >
      sh -c "migrate -path=/migrations
             -database postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable up"

volumes:
  db-data:
