basePath: /api
definitions:
  handlers.CreateCategoryBody:
    properties:
      name:
        type: string
      parentId:
        type: string
    required:
    - name
    type: object
  handlers.createProductBody:
    properties:
      categoryId:
        type: string
      description:
        type: string
      name:
        type: string
      price:
        format: int64
        type: integer
      stock:
        type: integer
    type: object
  handlers.updateCategoryBody:
    properties:
      name:
        type: string
      parentId:
        type: string
    type: object
  model.Product:
    properties:
      categoryId:
        type: string
      createdAt:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
      price:
        type: integer
      stock:
        type: integer
      updatedAt:
        type: string
    type: object
  model.ProductCategory:
    properties:
      createdAt:
        type: string
      id:
        type: string
      name:
        type: string
      parentId:
        type: string
      updatedAt:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is the API documentation for Savannah Store.
  title: Savannah Store API
  version: "1.0"
paths:
  /auth/login:
    get:
      description: Redirects the user to the Auth0/Google login page for authentication.
      produces:
      - application/json
      responses:
        "302":
          description: Redirects to Auth0/Google login page
          schema:
            type: string
        "500":
          description: Failed to initialize authenticator
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login endpoint
      tags:
      - auth
  /products:
    get:
      description: Returns paginated list of product
      parameters:
      - default: 10
        description: Number of products to return
        in: query
        name: limit
        type: integer
      - default: 0
        description: Offset for pagination
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Product'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: List product
      tags:
      - products
  /products/{id}:
    get:
      consumes:
      - application/json
      description: get product by its ID
      parameters:
      - description: Product Id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Product'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get product by ID
      tags:
      - products
  /products/categories:
    get:
      description: Returns paginated list of product categories
      parameters:
      - default: 10
        description: Number of categories to return
        in: query
        name: limit
        type: integer
      - default: 0
        description: Offset for pagination
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.ProductCategory'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: List product categories
      tags:
      - categories
  /products/categories/{id}:
    patch:
      consumes:
      - application/json
      description: Update a category by ID
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: string
      - description: Category data
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/handlers.updateCategoryBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ProductCategory'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update a category
      tags:
      - categories
  /products/categories/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: Category body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handlers.CreateCategoryBody'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.ProductCategory'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new category
      tags:
      - categories
  /products/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: Product body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handlers.createProductBody'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Product'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Add a new product
      tags:
      - products
swagger: "2.0"
